import turtle
t=turtle.Pen()
#turtle.width(3)
#turtle.color("red")
for x in range(80):
    t.forward(x)
    t.color("red")
    t.width(3)
    t.left(56)
turtle.penup()
turtle.goto(0,-10)
turtle.pendown()
turtle.width(6)
turtle.color("green")
turtle.left(270)
turtle.forward(200)
turtle.curve(40)